### ISSUE TITLE
Generator error. Unsupported type

### ISSUE THREAD

**Issue by sergey-morenets** [asyncapi/java-template#130]
#### Describe the bug

Error while using AsyncAPI Generator and java-template.

#### How to Reproduce

We tried to use AsyncAPI Generator: asyncapi generate fromTemplate spec.yml @asyncapi/java-template -p server=dev --force-write
But received an error: **Generator error. Unsupported type**
If we add --debug flag then another message is printed:
`File \asyncapi\index.js couldn't be found. Error: ENOENT: no such file or directory, stat '\asyncapi\index.js'`

#### Expected behavior

AsyncAPI Generator should generate Java service.
If there's an error in AsyncAPI document then java-template should clearly specify part of the document that contains error(s).

**Comment by predic8** [comment]
@sergey-morenets I have the same problem. It seems that the generator only supports strings and integer. float and number is not implemented.
