### ISSUE TITLE
Generate models only

### ISSUE THREAD

**Issue by black-snow** [asyncapi/java-template#138]
#### Reason/Context
I only want to generate the models and nothing else (for that's all I need). So I copied the whole template and stripped everything I don't need. But that's not a very stable solution assuming that I want to stay in sync with the original template.

Hence, it'd be nice if I could tell the generator to generate models only (like, for example, the OAS generator does it).

#### Description
We'd have to add a switch to not generate the other stuff. Also, `server` should become optional, and it shouldn't matter if the protocol is supported or not in that case.

**Comment by jonaslagoni** [comment]
Just jumping in, have you checked out [Modelina](https://github.com/asyncapi/modelina#asyncapi-cli)? 🙂

**Comment by black-snow** [comment]
Thanks, just found that after jumping through some hoops ;)
