### ISSUE TITLE
Complete the repository move

### ISSUE THREAD

**Issue by dalelane** [asyncapi/java-template#3]
This repository started life in https://github.com/ibm-messaging/mq-asyncapi-java-template 

The code history has been moved into this repo but there are likely a few loose ends left to tie up. 

We should review the other template projects to identify what they are and create a list of things we need to do to complete the move. 

For example, this might include automation and workflow things.

**Comment by dan-r** [comment]
A task that needs doing as part of this is adding an npm release script to publish to NPM.
The post-merge CI fails without this.

**Comment by derberg** [comment]
you folks need a hand here?

**Comment by dan-r** [comment]
Hi @derberg, is there anything else that you see us needing for an initial release in terms of repo setup, workflows etc?

**Comment by derberg** [comment]
I think it looks good, just not sure you need https://github.com/asyncapi/java-template/blob/master/package.json#L101 as I don't see you write about it in docs, so you can remove it and remove generator-hooks dependency

so go ahead and open `feat` PR, which also updates all entries from `https://ibm.biz/asyncapi-java-template` to `@asyncapi/java-template`.

we will see after merge if all is configured well, unless you did some dry tests already

**Comment by dan-r** [comment]
Changes made and feat PR in!
