### ISSUE TITLE
Use cipherSpec property from MQ binding

### ISSUE THREAD

**Issue by dan-r** [asyncapi/java-template#75]
For completeness, it would be good to parse the cipherSpec property from the spec and map this to the Java cipher suite as per https://www.ibm.com/docs/en/ibm-mq/9.3?topic=jms-tls-cipherspecs-ciphersuites-in-mq-classes

I'll give this a go for MQ, @dalelane I'm not sure if this is applicable/relevant to Kafka?

**Comment by dalelane** [comment]
> I'll give this a go for MQ, @dalelane I'm not sure if this is applicable/relevant to Kafka?

nope - Kafka uses a different approach
